---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bc-vrt-api-fluentd
  namespace: bccommon
secrets:
 - name: uispsecret
   namespace: bccommon
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: bc-vrt-api-fluentd
  namespace: bccommon
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bc-vrt-api-fluentd
  namespace: bccommon
roleRef:
  kind: ClusterRole
  name: bc-vrt-api-fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: bc-vrt-api-fluentd
  namespace: bccommon

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bc-vrt-api-fluentd
  namespace: bccommon
data:
  fluent.conf: |
   <system>
     log_level info
   </system>

   <source>
     @type tail
     path /var/log/containers/*_bcvrts_*.log
     exclude_path ["/var/log/containers/kube-*.log", "/var/log/containers/calico-*.log", "/var/log/containers/heapster-*.log", "/var/log/containers/etcd-*.log", "/var/log/containers/kubernetes-*.log", "/var/log/containers/fluentd-*.log", "/var/log/containers/monitoring-*.log", "/var/log/containers/custodian-agent-app-*","/var/log/containers/*_custodian_*","/var/log/containers/*_partner_*","/var/log/containers/*_uat-custodian_*"]
     pos_file /var/log/fluentd-containers.log.pos
     tag kubernetes.*
     read_from_head true
     multiline_flush_interval 3s
     <parse>
       @type json
     </parse>
     @label @INPUT
   </source>

   <label @INPUT>
     <filter kubernetes.**>
       @type concat
       key log
       multiline_start_regexp /^(?>\d\d){1,2}[-/](?:0?[1-9]|1[0-2])[-/](?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[T ](?:2[0123]|[01]?[0-9]):?(?:[0-5][0-9])(?::?(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?))?(?:Z|[+-](?:2[0123]|[01]?[0-9])(?::?(?:[0-5][0-9])))?/
       separator ""
       flush_interval 3s
       timeout_label @PARSE
     </filter>
     <match>
       @type relabel
       @label @PARSE
     </match>
   </label>

   <label @ERROR>
       <match **>
          @type stdout
       </match>
   </label>

   <label @PARSE>
     <filter kubernetes.**>
       @type parser
       key_name log
       inject_key_prefix log.
       <parse>
         @type multiline_grok
         grok_failure_key grokfailure
         <grok>
           pattern ^%{TIMESTAMP_ISO8601:timestamp_parsed}\s* \[%{DATA:thread}\] %{LOGLEVEL:level}  %{JAVACLASS} \- (?<message>.*)
         </grok>
         <grok>
           pattern ^%{TIMESTAMP_ISO8601:timestamp_parsed}\s* %{GREEDYDATA:message}
         </grok>
         <grok>
           pattern %{GREEDYDATA:message}
         </grok>
       </parse>
     </filter>
     <match>
       @type relabel
       @label @MAIN
     </match>
   </label>

   <label @TRANSFORM>
     <filter kubernetes.**>
       @type record_transformer
       enable_ruby
       <record>
         log.timestamp ${require 'date'; if record.dig("log.timestamp_parsed").include? "T"; return record.dig("log.timestamp_parsed"); else; return DateTime.parse(record.dig("log.timestamp_parsed"), '%Y-%m-%d %H:%M:%S,%L').strftime('%Y-%m-%dT%H:%M:%S.%L%z'); end;}
       </record>
       remove_keys log.timestamp_parsed
     </filter>
     <match>
       @type relabel
       @label @MAIN
     </match>
   </label>

   <label @MAIN>
       <filter kubernetes.**>
          @type kubernetes_metadata
       </filter>
       <match **>
          @type elasticsearch
          include_tag_key true
          host elasticsearch.partner
          port 9200
          logstash_format true
          time_key log.timestamp
          buffer_chunk_limit 1024M
          buffer_queue_limit 512
          flush_interval 5s
          max_retry_wait 30
          num_threads 8
          logstash_prefix vrt-api 
       </match>
   </label>
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bc-vrt-api-fluentd
  namespace: bccommon
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: bc-vrt-api-fluentd
      serviceAccountName: bc-vrt-api-fluentd
      #imagePullSecrets:
      #  - name: uispsecret
      containers:
        - name: fluentd
          image: kcsgbcdrg01.kcs:5000/vrt/fluentd:2.0.1
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            - name: config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            - name: mntebsdockercontaiers
              mountPath: /mnt/ebs1/docker/containers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: mntebsdockercontaiers
          hostPath:
              path: /mnt/ebs1/docker/containers
        - name: config
          configMap:
            name: bc-vrt-api-fluentd

