version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch_1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch_1
      - cluster.name=elasticsearch-docker-cluster
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=elasticsearch_1
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
      # - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - logging-network


  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana_1
    ports:
      - "5601:5601"
    # environment:
    #   - xpack.monitoring.ui.container.elasticsearch.enabled=true
    #   - ELASTIC_USERNAME=elastic
    #   - ELASTIC_PASSWORD=kuntrust
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
    networks:
      - logging-network


  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    container_name: logstash_1
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xmx1g -Xms1g
      - xpack.monitoring.enabled=true
      # - xpack.monitoring.elasticsearch.username=elastic
      # - xpack.monitoring.elasticsearch.password=kuntrust
    networks:
      - logging-network

networks:
  logging-network:
    driver: bridge





