version: '2'

networks:
  logging-network:

services:
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:7.4.2
    container_name: filebeat_1
    ports:
      - "9000:9000"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - logging-network